package justice_league_team

import justice_league_team.*;
import robocode.*;
import robocode.MessageEvent;

// Se debe incluir SIEMPRE la definición de esta consulta, la usa el robot para recuperar las acciones
query "consulta_acciones"
	accion: Accion_Team()
end

// 
// REGLAS
//

/*
// Quando receber cores, aplicá-las nas partes do robo
rule "ao receber cores -> pintar partes do robo"
	when
		$status: EstadoRobot()
		$mensagem: MessageEvent()
		eval($mensagem.getMessage() instanceof RobotoColors)
	then
		RobotColors c = (RobotColors) $mensagem.getMessage();
		$status.setBodyColor(c.bodyColor);
		$status.setGunColor(c.gunColor);
		$status.setRadarColor(c.radarColor);
		$status.setScanColor(c.scanColor);
		$status.setBulletColor(c.bulletColor);
		
		System.out.println("regla 0");
end
*/
// Regla de conveniencia: elimina acciones del mismo tipo con menor prioridad
// Si no se hiciera el robot ejecutaría la última acción insertada sin atender a su pioridad
rule "depurar acciones del mismo tipo"
	when
		$accion1: Accion_Team($tipo: tipo, $prioridad1: prioridad)
		$accion2: Accion_Team(tipo==$tipo, $prioridad2: prioridad)
		eval ($prioridad1 > $prioridad2)
	then
		retract($accion2);     // Elimina la accion menos prioritaria 
		System.out.println("regla 1");
end

// Quando receber a localização da vítima, move o canhão e atira no ponto
rule "ao receber um ponto -> mire e atire nele"
	when
		$status: EstadoRobot()
		$mensagem: MessageEvent()
		eval($mensagem.getMessage() instanceof Point)
	then
		Point p = (Point) $mensagem.getMessage();
		double theta = Auxiliar.anguloAbsoluto($status.getX(), $status.getY(), p.getX(), p.getY());
		
		insert(new Accion_Team(Accion_Team.GIRAR_CANON_DER, robocode.util.Utils.normalRelativeAngleDegrees(theta -  $status.getGunHeading()), 1));
		insert(new Accion_Team(Accion_Team.DISPARAR, Math.min(Rules.MAX_BULLET_POWER, 0.10*$status.getEnergy()), 1));
		System.out.println("regla 2");
end
